import type { ProjectInput } from "./types";

export const defaultProjectInput: ProjectInput = {
  projectInfo: {
    name: "Default engineering verification project",
    customer: "",
    city: "Уфа",
    notes: "Shared default for ProjectInput mapper tests.",
  },
  climate: {
    city: "Уфа",
    windLoadKpa: 0.3,
    snowLoadKpa: 2.45,
    terrainType: "B",
    responsibilityLevel: 1,
    responsibilityCoeff: 1,
  },
  geometry: {
    buildingSpanM: 24,
    buildingLengthM: 60,
    buildingHeightM: 12,
    roofSlopeDeg: 6,
    spanCount: "single",
    frameStepM: 6,
    facadePostStepM: 6,
    columnHeightM: 11.5,
    craneRailLevelM: 3.5,
  },
  roof: {
    roofType: "gable",
    roofConstruction: "С-П 150 мм",
    roofLoadKpa: 0.32028,
    deckProfile: "С-П 150 мм",
    snowBagMode: "none",
    snowRetentionPurlin: false,
    barrierPurlin: false,
  },
  walls: {
    wallConstruction: "профлист",
    wallLoadKpa: 0.105,
    openingWidthM: 3,
    openingHeightM: 1,
    windowType: 1,
  },
  cranes: {
    supportCrane: {
      enabled: false,
      capacityT: 5,
      count: "one",
      craneSpanM: 24,
      beamSpanM: 6,
      railLevelM: 3.5,
      wheelCount: 4,
      wheelBaseM: 3.7,
      maxWheelLoadKn: 60,
      trolleyWeightT: 2,
      craneWeightT: 10,
      railType: "Р50",
      dutyGroup: "3К",
    },
    hangingCrane: {
      enabled: false,
      capacityT: 2,
      count: 1,
    },
  },
  materials: {
    columnSteel: "С345",
    trussSteel: "С345",
    purlinSteel: "MP350",
    craneBeamSteel: "С345",
    windowRiegelSteel: "С245",
    beamCellSteel: "C345",
  },
  prices: {
    iBeamC245RubPerTon: 193200,
    iBeamC345RubPerTon: 203550,
    tubeC245RubPerTon: 167900,
    tubeC345RubPerTon: 179400,
    channelC245RubPerTon: 226260,
    channelC345RubPerTon: 236500,
    lstkMp350RubPerTon: 180000,
    lstkMp390RubPerTon: 190000,
  },
  calculationSettings: {
    maxUtilization: 0.85,
    purlinMinStepMm: 500,
    purlinMaxStepMm: 1500,
    deflectionLimit: 1 / 200,
    useOracleForCraneBeam: true,
    useOracleForWindowRiegel: true,
    useOracleForBeamCell: true,
  },
};
