/* eslint-disable */
// Generated by scripts/extract_purlin_workbook.py from Общий калькулятор прогонов v2.0.xlsx.
// Do not edit manually.

export const purlinWorkbook = {
  "sourceWorkbookSize": 37977330,
  "sourceWorkbook": "C:\\Users\\work\\Downloads\\Общий калькулятор прогонов v2.0.xlsx",
  "externalLinks": [
    "Z:/Предварительные расчеты/Калькуляторы/Таблица нагрузок по городам.xlsx",
    "Z:/Конструктивные расчеты/Прогоны/Для предрасчетов/Таблица нагрузок по городам.xlsx",
    "D:/Расчеты/Подбор прогонов v4.3.xlsx"
  ],
  "sheetStats": {
    "Лист1": {
      "rows": 160,
      "cols": 27,
      "nonEmpty": 1075,
      "formulas": 224,
      "merged": 13
    },
    "ЛСТК МП350": {
      "rows": 54,
      "cols": 2018,
      "nonEmpty": 88909,
      "formulas": 86247,
      "merged": 9
    },
    "ЛСТК МП390": {
      "rows": 54,
      "cols": 2013,
      "nonEmpty": 88908,
      "formulas": 86246,
      "merged": 9
    },
    "Расчет": {
      "rows": 441,
      "cols": 4941,
      "nonEmpty": 1923208,
      "formulas": 1910438,
      "merged": 11
    },
    "Лист2": {
      "rows": 26,
      "cols": 46,
      "nonEmpty": 878,
      "formulas": 0,
      "merged": 4
    },
    "Ветер СП": {
      "rows": 74,
      "cols": 39,
      "nonEmpty": 619,
      "formulas": 231,
      "merged": 19
    },
    "Ветер по СП РК EN": {
      "rows": 48,
      "cols": 33,
      "nonEmpty": 324,
      "formulas": 88,
      "merged": 2
    }
  },
  "options": {
    "responsibilityLevels": [
      1.1,
      1,
      0.8
    ],
    "roofTypes": [
      "односкатная",
      "двускатная"
    ],
    "terrainTypes": [
      "А",
      "В",
      "С"
    ],
    "windStandards": [
      "по СП РК EN",
      "по СП 20.13330.20ХХ"
    ],
    "roofConstructions": [
      "С-П 50 мм",
      "С-П 80 мм",
      "С-П 100 мм",
      "С-П 120 мм",
      "С-П 150 мм",
      "С-П 200 мм",
      "С-П 250 мм",
      "малоуклонная кровля с подв. п.",
      "малоуклонная кровля без подв. п.",
      "профлист",
      "наше 100 мм",
      "наше 150 мм",
      "наше 200 мм",
      "наше 250 мм",
      "наше 150 мм 1 слой ГВЛ",
      "наше 150 мм 2 слоя ГВЛ",
      "наше 200 мм 1 слой ГВЛ",
      "наше 200 мм 2 слоя ГВЛ",
      "наше 250 мм 1 слой ГВЛ",
      "наше 250 мм 2 слоя ГВЛ"
    ],
    "deckProfiles": [
      "С44-1000-0,5",
      "С44-1000-0,7",
      "Н60-845-0,7",
      "Н60-845-0,8"
    ],
    "snowBagOptions": [
      "нет",
      "вдоль здания",
      "поперек здания"
    ],
    "yesNo": [
      "да",
      "нет"
    ],
    "tieOptions": [
      "нет",
      1,
      2,
      3
    ],
    "lstkUtilizationModes": [
      "по умолчанию",
      90,
      95
    ]
  },
  "inputCells": {
    "city": "B2",
    "responsibilityLevel": "B3",
    "roofType": "B4",
    "buildingSpanM": "B7",
    "buildingLengthM": "B9",
    "buildingHeightM": "B10",
    "roofSlopeDeg": "B11",
    "frameStepM": "B12",
    "facadePostStepM": "B13",
    "terrainType": "B16",
    "windLoadKpa": "B17",
    "snowLoadKpa": "B18",
    "roofConstruction": "B19",
    "deckProfile": "B20",
    "snowBag": "B22",
    "heightDifferenceM": "B23",
    "existingBuildingSizeM": "B24",
    "maxStepMm": "B38",
    "minStepMm": "B39",
    "tieInstallation": "B41",
    "snowRetentionPurlin": "B44",
    "wallPurlin": "B45",
    "braceStepM": "B47",
    "maxUtilization": "D49",
    "priceIbeamC255": "C31",
    "priceIbeamC355": "C32",
    "priceTubeC245": "C33",
    "priceTubeC345": "C34",
    "priceChannelC245": "C35",
    "priceChannelC345": "C36"
  },
  "outputCells": {
    "calculatedSpanM": "B8",
    "roofLoadKpa": "D19",
    "mu2": "B25",
    "snowBagLengthM": "E24",
    "autoMaxStepMm": "B40",
    "loadAtMaxStepKpa": "E38",
    "loadAtMaxStepKgM2": "E39",
    "hotRolledTable": "A51:F60",
    "mp350Table": "C63:M65",
    "mp390Table": "C68:M70"
  },
  "defaultScenario": {
    "inputs": {
      "city": "Уфа",
      "responsibilityLevel": 1,
      "roofType": "двускатная",
      "buildingSpanM": 24,
      "buildingLengthM": 60,
      "buildingHeightM": 12,
      "roofSlopeDeg": 6,
      "frameStepM": 6,
      "facadePostStepM": 6,
      "terrainType": "В",
      "windLoadKpa": 0.6,
      "snowLoadKpa": 2.45,
      "roofConstruction": "С-П 150 мм",
      "deckProfile": "С44-1000-0,7",
      "snowBag": "нет",
      "heightDifferenceM": 4.5,
      "existingBuildingSizeM": 9.5,
      "maxStepMm": 1500,
      "minStepMm": 1500,
      "tieInstallation": "нет",
      "snowRetentionPurlin": "нет",
      "wallPurlin": "нет",
      "braceStepM": 3,
      "maxUtilization": 0.8,
      "priceIbeamC255": 150,
      "priceIbeamC355": 160,
      "priceTubeC245": 160,
      "priceTubeC345": 170,
      "priceChannelC245": 170,
      "priceChannelC345": 180
    },
    "expected": {
      "calculatedSpanM": 24,
      "roofLoadKpa": 0.32028,
      "mu2": 1,
      "snowBagLengthM": 24,
      "autoMaxStepMm": 1500,
      "loadAtMaxStepKpa": 5.122052722786631,
      "loadAtMaxStepKgM2": 512.2052722786631,
      "hotRolled": [
        [
          "кв.160х5",
          "С345",
          1500,
          26808.840000000007,
          444.4625
        ],
        [
          "пр.180х140х5",
          "С345",
          1500,
          26808.840000000007,
          444.5345
        ],
        [
          "пр.160х120х6",
          "С345",
          1500,
          28032.48,
          465.5245
        ],
        [
          "пр.180х100х6",
          "С345",
          1500,
          28032.48,
          465.53049999999996
        ],
        [
          "пр.200х160х5",
          "С245",
          1500,
          30257.28,
          472.3205
        ],
        [
          "кв.180х5",
          "С345",
          1500,
          30257.28,
          501.4665
        ],
        [
          "пр.200х160х5",
          "С345",
          1500,
          30257.28,
          501.5395
        ],
        [
          "кв.160х6",
          "С345",
          1500,
          32148.359999999997,
          533.4635000000001
        ],
        [
          "пр.180х140х6",
          "С345",
          1500,
          32148.359999999997,
          533.5355000000001
        ],
        [
          "кв.140х7",
          "С345",
          1500,
          32482.08,
          538.4595
        ]
      ],
      "mp350": [
        [
          "2ТПС",
          "#N/A",
          999999,
          "#N/A",
          999999,
          9999990,
          null,
          null,
          10004598,
          "#N/A",
          "#N/A"
        ],
        [
          "2ПС",
          "#N/A",
          999999,
          "#N/A",
          999999,
          9999990,
          null,
          null,
          10004598,
          "#N/A",
          "#N/A"
        ],
        [
          "Z",
          "Z 350х2,5",
          1500,
          11.15,
          1235.16,
          12351.6,
          309.60000000000036,
          12042,
          16959.6,
          1080,
          11.15
        ]
      ],
      "mp390": [
        [
          "2ТПС",
          "#N/A",
          999999,
          "#N/A",
          999999,
          9999990,
          null,
          null,
          10004598,
          "#N/A",
          "#N/A"
        ],
        [
          "2ПС",
          "#N/A",
          999999,
          "#N/A",
          999999,
          9999990,
          null,
          null,
          10004598,
          "#N/A",
          "#N/A"
        ],
        [
          "Z",
          "Z 350х2,5",
          1500,
          11.15,
          1235.16,
          12351.6,
          309.60000000000036,
          12042,
          16959.6,
          1080,
          11.15
        ]
      ]
    }
  }
} as const;
